package lcomCalculator;

public enum TokenType {
	
	IDENTIFIER, STRING, INTEGER,// identifiers and literals
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,LEFT_BRACKET,RIGHT_BRACKET,SEMICOLON,COMMA,EQUALS,FULL_STOP,//Symbols
	KEYWORD_IF,KEYWORD_ELSE,KEYWORD_INT,KEYWORD_STRING,KEYWORD_PUBLIC,KEYWORD_PRIVATE,KEYWORD_CLASS,KEYWORD_VOID,KEYWORD_STATIC,
	KEYWORD_FOR, KEYWORD_ABSTRACT, KEYWORD_INTERFACE,KEYWORD_NEW,KEYWORD_NULL// keywords

}
